### PR TITLE
Ntse fixcanclled keys

### PR DESCRIPTION
**Pull request by lwahlmeier**
Moved adding and removing from the selector only happen in the .select() call so its always happening on the same thread.

### CODE REVIEW

**Comment by jentfoo** [comment]
These changes look good to me.  I ran it through jenkins a lot and was able to produce another failure.  I don't think it is related to this set of change:

https://threadly.ci.cloudbees.com/job/litesockets-branch_build/21/testReport/junit/org.threadly.litesockets/ServerExecuterTests/manyClientsTest/

You think this failure is something different too?  Should I go ahead and merge this at least?

**Comment by lwahlmeier** [comment]
I will look into it but thats more then likely a performance thing.

**Comment by jentfoo** [comment]
If it is a performance thing, I would say increase your timeouts as we come across them.  I know most stuff in the threadly timeouts are around 10 seconds to be safe.  But that is part of the advantage of ec2, it helps us expose these race conditions by being so slow.

**Comment by lwahlmeier** [comment]
pushed up the timeout changes.  There are only a couple tests like that
one, its just checking concurrency when adding clients, but it is using 100
sockets so It does not surprise me that it could timeout on a slower
instance.

**Comment by jentfoo** [comment]
Looks good, no errors.  I will keep running tests for a little while and open any issues if I find any.  Awesome work!

**Pull request merged**
