### PR TITLE
added checkstyles to the code, fixed all the issue it found, moved to…

### PR DESCRIPTION
**Pull request by lwahlmeier**
@jentfoo this is pretty simple, once its merged I will take the release and write an issue to do the release.

### CODE REVIEW

**Comment by lwahlmeier** [comment]
@jentfoo also this moves to jaccooco, if I remember right that means jenkins needs updates as well.

**Comment by jentfoo** [comment]
I will need to update jenkins.  Take a look at my other PR (which will merge into this PR).  Once we close or merge that I will make the jenkins changes and make sure the build system works with this.

**Comment by lwahlmeier** [comment]
@jentfoo merged in your changes to the build scripts, everything looks good from my end.

**Comment by jentfoo** [comment]
I updated jenkins:
https://threadly.ci.cloudbees.com/job/litesockets-branch_build/47/jacoco/

FWIW, the thresholds for complexity is 75, line is 90, and method is 90.  So it's highlighting those as lower coverage.  Let me know if you think I should lower the thresholds, but it seems like it gives us something to work towards.

**Pull request merged**
